//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityPerUserTable
    {
        public int ActivityID { get; set; }
        public string UserName { get; set; }
        public Nullable<bool> ReminderSet { get; set; }
        public Nullable<System.DateTime> FlagDueBy { get; set; }
        public Nullable<System.DateTime> ReminderTime { get; set; }
        public Nullable<int> ReminderMinutesBeforeStart { get; set; }
        public Nullable<bool> ReminderOverrideDefault { get; set; }
        public Nullable<bool> ReminderPlaySound { get; set; }
        public string ReminderSoundFile { get; set; }
        public Nullable<byte> FlagStatus { get; set; }
        public string FollowUpFlag { get; set; }
        public Nullable<int> TodoItemFlags { get; set; }
        public byte[] SwappedTodoStore { get; set; }
        public byte[] SwappedTodoData { get; set; }
        public string TodoTitle { get; set; }
        public Nullable<System.DateTime> DueDate { get; set; }
        public Nullable<System.DateTime> StartDate { get; set; }
        public Nullable<System.DateTime> CommonStart { get; set; }
        public Nullable<System.DateTime> CommonEnd { get; set; }
    
        public virtual ActivitiesTable ActivitiesTable { get; set; }
    }
}
