//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesOpportunityView
    {
        public Nullable<int> ActivityID { get; set; }
        public Nullable<System.Guid> LinkGUID { get; set; }
        public bool IsDeletedLocally { get; set; }
        public int ContactServiceID { get; set; }
        public Nullable<System.Guid> ParentEntryGUID { get; set; }
        public Nullable<System.Guid> GrandParentEntryGUID { get; set; }
        public Nullable<System.Guid> GreatGrandParentEntryGUID { get; set; }
        public Nullable<System.Guid> ActivityGUID { get; set; }
        public int ActivityType { get; set; }
        public string ActivityTypeName { get; set; }
        public Nullable<bool> ActivityIsDeletedLocally { get; set; }
        public string Subject { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ActivityStartTime { get; set; }
        public Nullable<int> ActivityDuration { get; set; }
        public string PhoneNumCalled { get; set; }
        public string FromName { get; set; }
        public string ToNames { get; set; }
        public string CCNames { get; set; }
        public Nullable<System.DateTime> ActivitySentTime { get; set; }
        public string ActivityStatus { get; set; }
        public string ActivityPriority { get; set; }
        public Nullable<byte> ActivityPercentComplete { get; set; }
        public string ActivityLocation { get; set; }
        public string LinkToOriginal { get; set; }
        public Nullable<short> LinkToOriginalType { get; set; }
        public string ActivityNote { get; set; }
        public Nullable<int> IconIndex { get; set; }
        public Nullable<System.DateTime> MessageDeliveryTime { get; set; }
    }
}
