//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivitiesTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ActivitiesTable()
        {
            this.ActivitiesAdditionalPropertyBags = new HashSet<ActivitiesAdditionalPropertyBag>();
            this.ActivityAttachments = new HashSet<ActivityAttachment>();
            this.ActivityCategoriesTables = new HashSet<ActivityCategoriesTable>();
            this.ActivityContacts = new HashSet<ActivityContact>();
            this.ActivityPerUserTables = new HashSet<ActivityPerUserTable>();
            this.CampaignRecipients = new HashSet<CampaignRecipient>();
        }
    
        public int ActivityID { get; set; }
        public System.Guid ActivityGUID { get; set; }
        public string Subject { get; set; }
        public string ActivityNote { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public int ActivityType { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ActivitySentTime { get; set; }
        public Nullable<System.DateTime> ActivityDate { get; set; }
        public string FromName { get; set; }
        public string ToNames { get; set; }
        public string LinkToOriginal { get; set; }
        public Nullable<System.DateTime> ActivityStartTime { get; set; }
        public Nullable<int> ActivityDuration { get; set; }
        public string PhoneNumCalled { get; set; }
        public string PersonCalled { get; set; }
        public string CCNames { get; set; }
        public string ActivityLocation { get; set; }
        public Nullable<System.DateTime> ActivityEndTime { get; set; }
        public string ActivityStatus { get; set; }
        public string ActivityPriority { get; set; }
        public Nullable<byte> ActivityPercentComplete { get; set; }
        public Nullable<System.Guid> OwnerID { get; set; }
        public Nullable<int> IconIndex { get; set; }
        public Nullable<System.DateTime> MessageDeliveryTime { get; set; }
        public Nullable<int> Importance { get; set; }
        public string TimeSlipId { get; set; }
        public Nullable<bool> IsBillable { get; set; }
        public Nullable<int> MessageFlags { get; set; }
        public Nullable<System.DateTime> ModifiedOnUTC { get; set; }
        public Nullable<int> SideEffects { get; set; }
        public byte[] GlobalObjectID { get; set; }
        public byte[] CompressedRichText { get; set; }
        public string CallType { get; set; }
        public Nullable<System.Guid> ReferredEntryId { get; set; }
        public Nullable<int> AttachmentCount { get; set; }
        public byte[] SearchKey { get; set; }
        public Nullable<long> Version { get; set; }
        public Nullable<short> LinkToOriginalType { get; set; }
        public bool IsDeletedLocally { get; set; }
        public long ContentVersion { get; set; }
        public int CreationReplicaKey { get; set; }
        public long CreationTickCount { get; set; }
        public int ChangeReplicaKey { get; set; }
        public long ChangeTickCount { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public Nullable<byte> FolderType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesAdditionalPropertyBag> ActivitiesAdditionalPropertyBags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAttachment> ActivityAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityCategoriesTable> ActivityCategoriesTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityContact> ActivityContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityPerUserTable> ActivityPerUserTables { get; set; }
        public virtual CampaignQueryTable CampaignQueryTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<CampaignRecipient> CampaignRecipients { get; set; }
        public virtual CampaignTable CampaignTable { get; set; }
        public virtual ProjectTaskTable ProjectTaskTable { get; set; }
    }
}
