//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ActivityTypesTable
    {
        public int ActivityTypeID { get; set; }
        public string ActivityTypeName { get; set; }
        public string ActivityTypeLocalizedName { get; set; }
        public string ActivityTypeDescription { get; set; }
    }
}
