//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class Attachment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Attachment()
        {
            this.ActivityAttachments = new HashSet<ActivityAttachment>();
            this.ContactAttachments = new HashSet<ContactAttachment>();
        }
    
        public int ID { get; set; }
        public Nullable<bool> AttachmentContactPhoto { get; set; }
        public Nullable<int> AttachmentFlags { get; set; }
        public Nullable<bool> AttachmentHidden { get; set; }
        public byte[] AttachDataBin { get; set; }
        public byte[] AttachEncoding { get; set; }
        public string AttachExtension { get; set; }
        public string AttachFileName { get; set; }
        public string AttachLongFileName { get; set; }
        public Nullable<int> AttachMethod { get; set; }
        public byte[] AttachRendering { get; set; }
        public Nullable<int> AttachSize { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string DisplayName { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<int> RenderingPosition { get; set; }
        public Nullable<System.Guid> EntryGUID { get; set; }
        public Nullable<bool> AttachmentBusinessCardPicture { get; set; }
        public Nullable<int> AttachmentLinkID { get; set; }
        public Nullable<int> AttachFlags { get; set; }
        public string AttachLongPathName { get; set; }
        public string AttachPathName { get; set; }
        public byte[] PRAttachTag { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityAttachment> ActivityAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactAttachment> ContactAttachments { get; set; }
    }
}
