//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignQueryTable
    {
        public int ActivityID { get; set; }
        public string RecipientQuery { get; set; }
    
        public virtual ActivitiesTable ActivitiesTable { get; set; }
    }
}
