//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class CampaignsToExportForEntityView
    {
        public System.Guid ActivityGUID { get; set; }
        public Nullable<long> Version { get; set; }
        public System.Guid LinkGUID { get; set; }
        public Nullable<long> HistoryVersion { get; set; }
    }
}
