//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactProjectIMAPIView
    {
        public Nullable<int> ViewRowID { get; set; }
        public Nullable<int> ContactServiceID { get; set; }
        public Nullable<bool> IsDeletedLocally { get; set; }
        public Nullable<bool> IsCAO { get; set; }
        public Nullable<int> EntityTypeCode { get; set; }
        public int ActivityType { get; set; }
        public Nullable<long> Version { get; set; }
        public Nullable<System.Guid> Field4089 { get; set; }
        public string Field55 { get; set; }
        public string Field14871 { get; set; }
        public string Field14856 { get; set; }
        public string Field32769 { get; set; }
        public Nullable<System.Guid> Field37406 { get; set; }
    }
}
