//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMainTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ContactMainTable()
        {
            this.ActivityContacts = new HashSet<ActivityContact>();
            this.ActivityContacts1 = new HashSet<ActivityContact>();
            this.ActivityContacts2 = new HashSet<ActivityContact>();
            this.ContactAdditionalPropertyBags = new HashSet<ContactAdditionalPropertyBag>();
            this.ContactAttachments = new HashSet<ContactAttachment>();
            this.ContactCategoriesTables = new HashSet<ContactCategoriesTable>();
            this.ContactMainTable1 = new HashSet<ContactMainTable>();
            this.ContactMainTable11 = new HashSet<ContactMainTable>();
            this.ContactPerUserTables = new HashSet<ContactPerUserTable>();
            this.EAAOptinEmailTables = new HashSet<EAAOptinEmailTable>();
            this.EAAProjectSubjects = new HashSet<EAAProjectSubject>();
            this.EntityReferences = new HashSet<EntityReference>();
            this.EntityReferences1 = new HashSet<EntityReference>();
            this.OpportunityProductsTables = new HashSet<OpportunityProductsTable>();
            this.ProjectContacts = new HashSet<ProjectContact>();
            this.ProjectContacts1 = new HashSet<ProjectContact>();
        }
    
        public int ContactServiceID { get; set; }
        public int Type { get; set; }
        public Nullable<int> ParentContactServiceID { get; set; }
        public Nullable<int> ParentType { get; set; }
        public Nullable<int> GrandParentContactServiceID { get; set; }
        public Nullable<int> GrandParentType { get; set; }
        public Nullable<System.Guid> GrandParentEntryID { get; set; }
        public Nullable<System.Guid> EntryGUID { get; set; }
        public Nullable<System.Guid> ParentEntryID { get; set; }
        public string FullName { get; set; }
        public string JobTitle { get; set; }
        public string CompanyName { get; set; }
        public string FileAs { get; set; }
        public bool Active { get; set; }
        public string PaymentStatus { get; set; }
        public string Rating { get; set; }
        public string Subject { get; set; }
        public Nullable<byte> MailingAddressIndicator { get; set; }
        public string BusinessFaxNum { get; set; }
        public string WorkPhoneNum { get; set; }
        public string PhoneNum2 { get; set; }
        public string CompanyMainPhoneNum { get; set; }
        public string PhoneNum3 { get; set; }
        public string HomePhoneNum { get; set; }
        public string MobilePhoneNum { get; set; }
        public string OtherFaxNum { get; set; }
        public string OtherPhoneNum { get; set; }
        public string EmailAddress1 { get; set; }
        public string EmailAddress2 { get; set; }
        public string EmailAddress3 { get; set; }
        public string WebAddress { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<int> MessageFlags { get; set; }
        public string BusinessAddress { get; set; }
        public string PostalAddress { get; set; }
        public Nullable<int> IconIndex { get; set; }
        public string PostalAddressZip { get; set; }
        public byte[] BusinessCardDisplayDefinition { get; set; }
        public Nullable<bool> HasPicture { get; set; }
        public Nullable<System.DateTime> ModifiedOnUTC { get; set; }
        public Nullable<int> SideEffects { get; set; }
        public string LeadScore { get; set; }
        public bool LeadScoreCalculated { get; set; }
        public Nullable<int> AttachmentCount { get; set; }
        public byte[] ReferenceEntryID { get; set; }
        public Nullable<int> OpportunityOrdinal { get; set; }
        public Nullable<int> IrisSubType { get; set; }
        public byte[] SearchKey { get; set; }
        public string BusinessHomePage { get; set; }
        public Nullable<int> Importance { get; set; }
        public Nullable<System.Guid> PrimaryContactGUID { get; set; }
        public Nullable<System.DateTime> LastAccessTime { get; set; }
        public bool IsDeletedLocally { get; set; }
        public long Version { get; set; }
        public long ContentVersion { get; set; }
        public int CreationReplicaKey { get; set; }
        public long CreationTickCount { get; set; }
        public int ChangeReplicaKey { get; set; }
        public long ChangeTickCount { get; set; }
        public Nullable<byte> ItemType { get; set; }
        public Nullable<byte> FolderType { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityContact> ActivityContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityContact> ActivityContacts1 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivityContact> ActivityContacts2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactAdditionalPropertyBag> ContactAdditionalPropertyBags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactAttachment> ContactAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactCategoriesTable> ContactCategoriesTables { get; set; }
        public virtual ContactDetailsTable ContactDetailsTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactMainTable> ContactMainTable1 { get; set; }
        public virtual ContactMainTable ContactMainTable2 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactMainTable> ContactMainTable11 { get; set; }
        public virtual ContactMainTable ContactMainTable3 { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactPerUserTable> ContactPerUserTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EAAOptinEmailTable> EAAOptinEmailTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EAAProjectSubject> EAAProjectSubjects { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityReference> EntityReferences { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityReference> EntityReferences1 { get; set; }
        public virtual LeadScoringField LeadScoringField { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<OpportunityProductsTable> OpportunityProductsTables { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectContact> ProjectContacts { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectContact> ProjectContacts1 { get; set; }
        public virtual SalesActivityField SalesActivityField { get; set; }
        public virtual UserField UserField { get; set; }
    }
}
