//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactAttachment
    {
        public int ID { get; set; }
        public int ContactServiceID { get; set; }
        public Nullable<int> DataID { get; set; }
        public int AttachmentID { get; set; }
    
        public virtual Attachment Attachment { get; set; }
        public virtual ContactMainTable ContactMainTable { get; set; }
        public virtual EntityUserField EntityUserField { get; set; }
    }
}
