//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactsComputedPropertiesView
    {
        public int ContactServiceID { get; set; }
        public Nullable<System.Guid> EntryGUID { get; set; }
        public Nullable<bool> DeletedItemsSummaryItem { get; set; }
        public string MessageClass { get; set; }
        public int EntityTypeCode { get; set; }
        public int CoreEntityType { get; set; }
        public int FolderTypeCode { get; set; }
        public Nullable<System.Guid> GrandParentEntryID { get; set; }
        public Nullable<System.Guid> GreatGrandParentEntryID { get; set; }
        public string EntryTypeLocalized { get; set; }
        public string EntryTypeLocaleIndependent { get; set; }
        public Nullable<int> StoreEntryID { get; set; }
        public string PrimaryContactName { get; set; }
        public string ParentDisplayName { get; set; }
        public Nullable<decimal> ExpectedRevenue { get; set; }
        public string Account { get; set; }
        public Nullable<int> ParentType { get; set; }
        public Nullable<int> GrandParentType { get; set; }
        public string OpportunityParent { get; set; }
        public string NormalizedSubject { get; set; }
        public Nullable<bool> HasProducts { get; set; }
        public Nullable<int> ReferredByType { get; set; }
        public string ReferredBy { get; set; }
        public Nullable<System.Guid> ReferredByEntryGUID { get; set; }
        public Nullable<bool> HasAttach { get; set; }
        public byte[] ContactPicture { get; set; }
        public byte[] BusinessCardPicture { get; set; }
        public Nullable<int> FlagIcon { get; set; }
    }
}
