//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactMainView
    {
        public int ContactServiceID { get; set; }
        public long Version { get; set; }
        public long ContentVersion { get; set; }
        public int Type { get; set; }
        public bool IsDeletedLocally { get; set; }
        public string FirstName { get; set; }
        public string LastName { get; set; }
        public string MiddleName { get; set; }
        public string Suffix { get; set; }
        public string Prefix { get; set; }
        public string FileAs { get; set; }
        public string FullName { get; set; }
        public string Subject { get; set; }
        public Nullable<System.Guid> EntryGUID { get; set; }
        public Nullable<System.Guid> ParentEntryID { get; set; }
        public string JobTitle { get; set; }
        public string Profession { get; set; }
        public string CompanyName { get; set; }
        public string Department { get; set; }
        public Nullable<System.DateTime> Birthday { get; set; }
        public Nullable<System.DateTime> WeddingAnniversary { get; set; }
        public string ManagerName { get; set; }
        public string AssistantName { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public Nullable<System.DateTime> LastAccessTime { get; set; }
        public string PrefContactMethod { get; set; }
        public Nullable<bool> DoNotEmail { get; set; }
        public Nullable<bool> DoNotFax { get; set; }
        public Nullable<bool> DoNotCall { get; set; }
        public Nullable<bool> DoNotSendLetter { get; set; }
        public Nullable<System.Guid> PrimaryContactGUID { get; set; }
        public string PaymentStatus { get; set; }
        public string Rating { get; set; }
        public bool Active { get; set; }
        public string CustomerID { get; set; }
        public string Territory { get; set; }
        public string TypeOfEntity { get; set; }
        public string WebAddress { get; set; }
        public Nullable<byte> FlagStatus { get; set; }
        public string FollowUpFlag { get; set; }
        public Nullable<int> MessageFlags { get; set; }
        public Nullable<int> ParentContactServiceID { get; set; }
        public string ReferredBy { get; set; }
        public string LeadSource { get; set; }
        public string AreaOfInterest { get; set; }
        public string LeadScore { get; set; }
        public bool LeadScoreCalculated { get; set; }
        public Nullable<System.Guid> GrandParentEntryID { get; set; }
        public Nullable<int> ParentType { get; set; }
        public Nullable<int> GrandParentContactServiceID { get; set; }
    }
}
