//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactPicklistValuesView
    {
        public int ContactServiceID { get; set; }
        public Nullable<short> PrefContactMethodOrderID { get; set; }
        public Nullable<short> PaymentStatusOrderID { get; set; }
        public Nullable<short> RatingOrderID { get; set; }
        public Nullable<short> LeadSourceOrderID { get; set; }
        public Nullable<short> TerritoryOrderID { get; set; }
        public Nullable<short> TypeOfEntityOrderID { get; set; }
    }
}
