//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class DataTypesTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public DataTypesTable()
        {
            this.ActivitiesAdditionalPropertyBags = new HashSet<ActivitiesAdditionalPropertyBag>();
            this.ContactAdditionalPropertyBags = new HashSet<ContactAdditionalPropertyBag>();
            this.UserFieldDataTypes = new HashSet<UserFieldDataType>();
        }
    
        public short DataTypeID { get; set; }
        public string DataTypeName { get; set; }
        public string DataTypeDescription { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ActivitiesAdditionalPropertyBag> ActivitiesAdditionalPropertyBags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactAdditionalPropertyBag> ContactAdditionalPropertyBags { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFieldDataType> UserFieldDataTypes { get; set; }
    }
}
