//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntityUserField
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public EntityUserField()
        {
            this.ContactAttachments = new HashSet<ContactAttachment>();
            this.EntityReferences = new HashSet<EntityReference>();
        }
    
        public int EntityType { get; set; }
        public System.Guid FieldGUID { get; set; }
        public short UserFieldIndex { get; set; }
        public int DataID { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ContactAttachment> ContactAttachments { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityReference> EntityReferences { get; set; }
        public virtual EntityTypesTable EntityTypesTable { get; set; }
        public virtual UserFieldDefinition UserFieldDefinition { get; set; }
    }
}
