//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class EntitySubTypesTable
    {
        public int SubTypeID { get; set; }
        public int EntityType { get; set; }
        public string MessageClass { get; set; }
        public string SubTypeName { get; set; }
        public string PluralName { get; set; }
        public byte[] IconResources { get; set; }
        public System.Guid SubTypeGUID { get; set; }
        public long Version { get; set; }
    
        public virtual EntityTypesTable EntityTypesTable { get; set; }
    }
}
