//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class LeadScoringField
    {
        public int ContactServiceID { get; set; }
        public Nullable<System.DateTime> LeadScoringField1 { get; set; }
        public Nullable<System.DateTime> LeadScoringField2 { get; set; }
        public Nullable<System.DateTime> LeadScoringField3 { get; set; }
        public Nullable<System.DateTime> LeadScoringField4 { get; set; }
        public Nullable<System.DateTime> LeadScoringField5 { get; set; }
        public Nullable<System.DateTime> LeadScoringField6 { get; set; }
        public Nullable<System.DateTime> LeadScoringField7 { get; set; }
        public Nullable<System.DateTime> LeadScoringField8 { get; set; }
        public Nullable<System.DateTime> LeadScoringField9 { get; set; }
        public Nullable<System.DateTime> LeadScoringField10 { get; set; }
        public Nullable<System.DateTime> LeadScoringField11 { get; set; }
        public Nullable<System.DateTime> LeadScoringField12 { get; set; }
        public Nullable<System.DateTime> LeadScoringField13 { get; set; }
        public Nullable<System.DateTime> LeadScoringField14 { get; set; }
        public Nullable<System.DateTime> LeadScoringField15 { get; set; }
        public Nullable<System.DateTime> LeadScoringField16 { get; set; }
        public Nullable<System.DateTime> LeadScoringField17 { get; set; }
        public Nullable<System.DateTime> LeadScoringField18 { get; set; }
        public Nullable<System.DateTime> LeadScoringField19 { get; set; }
        public Nullable<System.DateTime> LeadScoringField20 { get; set; }
        public Nullable<System.DateTime> LeadScoringField21 { get; set; }
        public Nullable<System.DateTime> LeadScoringField22 { get; set; }
        public Nullable<System.DateTime> LeadScoringField23 { get; set; }
        public Nullable<System.DateTime> LeadScoringField24 { get; set; }
        public Nullable<System.DateTime> LeadScoringField25 { get; set; }
        public Nullable<System.DateTime> LeadScoringField26 { get; set; }
        public Nullable<System.DateTime> LeadScoringField27 { get; set; }
        public Nullable<System.DateTime> LeadScoringField28 { get; set; }
        public Nullable<System.DateTime> LeadScoringField29 { get; set; }
        public Nullable<System.DateTime> LeadScoringField30 { get; set; }
        public Nullable<System.DateTime> LeadScoringField31 { get; set; }
        public Nullable<System.DateTime> LeadScoringField32 { get; set; }
        public Nullable<System.DateTime> LeadScoringField33 { get; set; }
        public Nullable<System.DateTime> LeadScoringField34 { get; set; }
        public Nullable<System.DateTime> LeadScoringField35 { get; set; }
        public Nullable<System.DateTime> LeadScoringField36 { get; set; }
        public Nullable<System.DateTime> LeadScoringField37 { get; set; }
        public Nullable<System.DateTime> LeadScoringField38 { get; set; }
        public Nullable<System.DateTime> LeadScoringField39 { get; set; }
        public Nullable<System.DateTime> LeadScoringField40 { get; set; }
        public Nullable<System.DateTime> LeadScoringField41 { get; set; }
        public Nullable<System.DateTime> LeadScoringField42 { get; set; }
        public Nullable<System.DateTime> LeadScoringField43 { get; set; }
        public Nullable<System.DateTime> LeadScoringField44 { get; set; }
        public Nullable<System.DateTime> LeadScoringField45 { get; set; }
        public Nullable<System.DateTime> LeadScoringField46 { get; set; }
        public Nullable<System.DateTime> LeadScoringField47 { get; set; }
        public Nullable<System.DateTime> LeadScoringField48 { get; set; }
        public Nullable<System.DateTime> LeadScoringField49 { get; set; }
        public Nullable<System.DateTime> LeadScoringField50 { get; set; }
    
        public virtual ContactMainTable ContactMainTable { get; set; }
    }
}
