//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class NamePropSetIDMapping
    {
        public int ID { get; set; }
        public Nullable<System.Guid> NamePropSet { get; set; }
        public Nullable<byte> NameKind { get; set; }
        public string Name { get; set; }
    }
}
