//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class OpportunityFullView
    {
        public int ContactServiceID { get; set; }
        public string OpportunityType { get; set; }
        public string OpportunityStage { get; set; }
        public Nullable<System.DateTime> OpportunityCloseDate { get; set; }
        public Nullable<byte> OpportunityStatus { get; set; }
        public Nullable<double> Probability { get; set; }
        public Nullable<decimal> OpportunityTotal { get; set; }
        public Nullable<decimal> OpportunityExpectedRevenue { get; set; }
        public Nullable<decimal> OpportunityTotalDiscount { get; set; }
        public Nullable<decimal> OpportunityGrossMargin { get; set; }
        public Nullable<decimal> OpportunityExpectedGrossMargin { get; set; }
        public string ReferredBy { get; set; }
        public Nullable<System.Guid> ReferredEntryId { get; set; }
        public string LeadSource { get; set; }
        public string AreaOfInterest { get; set; }
        public string Competition { get; set; }
        public string OpportunityName { get; set; }
        public Nullable<System.Guid> ParentEntryID { get; set; }
        public string CreatedBy { get; set; }
        public Nullable<System.DateTime> CreatedOn { get; set; }
        public string ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedOn { get; set; }
        public string AssignedTo { get; set; }
        public bool IsDeletedLocally { get; set; }
        public Nullable<System.Guid> EntryGUID { get; set; }
    }
}
