//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectComputedPropertiesView
    {
        public int ContactServiceID { get; set; }
        public Nullable<bool> DeletedItemsSummaryItem { get; set; }
        public string MessageClass { get; set; }
        public int EntityTypeCode { get; set; }
        public int CoreEntityType { get; set; }
        public int FolderTypeCode { get; set; }
        public Nullable<System.Guid> GrandParentEntryID { get; set; }
        public string EntryTypeLocalized { get; set; }
        public string EntryTypeLocaleIndependent { get; set; }
        public string ParentDisplayName { get; set; }
        public Nullable<int> ParentType { get; set; }
        public Nullable<int> GrandParentType { get; set; }
        public string OpportunityParent { get; set; }
        public string NormalizedSubject { get; set; }
        public Nullable<bool> HasAttach { get; set; }
        public Nullable<int> FlagIcon { get; set; }
    }
}
