//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ProjectTemplateTable
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ProjectTemplateTable()
        {
            this.ProjectTemplateTaskTables = new HashSet<ProjectTemplateTaskTable>();
        }
    
        public System.Guid TemplateGUID { get; set; }
        public string TemplateName { get; set; }
        public Nullable<int> Duration { get; set; }
        public string Type { get; set; }
        public string Priority { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<ProjectTemplateTaskTable> ProjectTemplateTaskTables { get; set; }
    }
}
