//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReportExportView
    {
        public System.Guid ReportID { get; set; }
        public string ReportName { get; set; }
        public int BaseEntityType { get; set; }
        public int ReportType { get; set; }
        public byte[] ReportObject { get; set; }
        public int Sequence { get; set; }
        public bool IsLeadReport { get; set; }
    }
}
