//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class SalesActivityField
    {
        public int ContactServiceID { get; set; }
        public Nullable<System.DateTime> SalesActivityField1 { get; set; }
        public Nullable<System.DateTime> SalesActivityField2 { get; set; }
        public Nullable<System.DateTime> SalesActivityField3 { get; set; }
        public Nullable<System.DateTime> SalesActivityField4 { get; set; }
        public Nullable<System.DateTime> SalesActivityField5 { get; set; }
        public Nullable<System.DateTime> SalesActivityField6 { get; set; }
        public Nullable<System.DateTime> SalesActivityField7 { get; set; }
        public Nullable<System.DateTime> SalesActivityField8 { get; set; }
        public Nullable<System.DateTime> SalesActivityField9 { get; set; }
        public Nullable<System.DateTime> SalesActivityField10 { get; set; }
        public Nullable<System.DateTime> SalesActivityField11 { get; set; }
        public Nullable<System.DateTime> SalesActivityField12 { get; set; }
        public Nullable<System.DateTime> SalesActivityField13 { get; set; }
        public Nullable<System.DateTime> SalesActivityField14 { get; set; }
        public Nullable<System.DateTime> SalesActivityField15 { get; set; }
        public Nullable<System.DateTime> SalesActivityField16 { get; set; }
        public Nullable<System.DateTime> SalesActivityField17 { get; set; }
        public Nullable<System.DateTime> SalesActivityField18 { get; set; }
        public Nullable<System.DateTime> SalesActivityField19 { get; set; }
        public Nullable<System.DateTime> SalesActivityField20 { get; set; }
        public Nullable<System.DateTime> SalesActivityField21 { get; set; }
        public Nullable<System.DateTime> SalesActivityField22 { get; set; }
        public Nullable<System.DateTime> SalesActivityField23 { get; set; }
        public Nullable<System.DateTime> SalesActivityField24 { get; set; }
        public Nullable<System.DateTime> SalesActivityField25 { get; set; }
        public Nullable<System.DateTime> SalesActivityField26 { get; set; }
        public Nullable<System.DateTime> SalesActivityField27 { get; set; }
        public Nullable<System.DateTime> SalesActivityField28 { get; set; }
        public Nullable<System.DateTime> SalesActivityField29 { get; set; }
        public Nullable<System.DateTime> SalesActivityField30 { get; set; }
        public Nullable<System.DateTime> SalesActivityField31 { get; set; }
        public Nullable<System.DateTime> SalesActivityField32 { get; set; }
        public Nullable<System.DateTime> SalesActivityField33 { get; set; }
        public Nullable<System.DateTime> SalesActivityField34 { get; set; }
        public Nullable<System.DateTime> SalesActivityField35 { get; set; }
        public Nullable<System.DateTime> SalesActivityField36 { get; set; }
        public Nullable<System.DateTime> SalesActivityField37 { get; set; }
        public Nullable<System.DateTime> SalesActivityField38 { get; set; }
        public Nullable<System.DateTime> SalesActivityField39 { get; set; }
        public Nullable<System.DateTime> SalesActivityField40 { get; set; }
        public Nullable<System.DateTime> SalesActivityField41 { get; set; }
        public Nullable<System.DateTime> SalesActivityField42 { get; set; }
        public Nullable<System.DateTime> SalesActivityField43 { get; set; }
        public Nullable<System.DateTime> SalesActivityField44 { get; set; }
        public Nullable<System.DateTime> SalesActivityField45 { get; set; }
        public Nullable<System.DateTime> SalesActivityField46 { get; set; }
        public Nullable<System.DateTime> SalesActivityField47 { get; set; }
        public Nullable<System.DateTime> SalesActivityField48 { get; set; }
        public Nullable<System.DateTime> SalesActivityField49 { get; set; }
        public Nullable<System.DateTime> SalesActivityField50 { get; set; }
        public Nullable<System.DateTime> SalesActivityField51 { get; set; }
        public Nullable<System.DateTime> SalesActivityField52 { get; set; }
        public Nullable<System.DateTime> SalesActivityField53 { get; set; }
        public Nullable<System.DateTime> SalesActivityField54 { get; set; }
        public Nullable<System.DateTime> SalesActivityField55 { get; set; }
        public Nullable<System.DateTime> SalesActivityField56 { get; set; }
        public Nullable<System.DateTime> SalesActivityField57 { get; set; }
        public Nullable<System.DateTime> SalesActivityField58 { get; set; }
        public Nullable<System.DateTime> SalesActivityField59 { get; set; }
        public Nullable<System.DateTime> SalesActivityField60 { get; set; }
        public Nullable<System.DateTime> SalesActivityField61 { get; set; }
        public Nullable<System.DateTime> SalesActivityField62 { get; set; }
        public Nullable<System.DateTime> SalesActivityField63 { get; set; }
        public Nullable<System.DateTime> SalesActivityField64 { get; set; }
        public Nullable<System.DateTime> SalesActivityField65 { get; set; }
        public Nullable<System.DateTime> SalesActivityField66 { get; set; }
        public Nullable<System.DateTime> SalesActivityField67 { get; set; }
        public Nullable<System.DateTime> SalesActivityField68 { get; set; }
        public Nullable<System.DateTime> SalesActivityField69 { get; set; }
        public Nullable<System.DateTime> SalesActivityField70 { get; set; }
        public Nullable<System.DateTime> SalesActivityField71 { get; set; }
        public Nullable<System.DateTime> SalesActivityField72 { get; set; }
        public Nullable<System.DateTime> SalesActivityField73 { get; set; }
        public Nullable<System.DateTime> SalesActivityField74 { get; set; }
        public Nullable<System.DateTime> SalesActivityField75 { get; set; }
        public Nullable<System.DateTime> SalesActivityField76 { get; set; }
        public Nullable<System.DateTime> SalesActivityField77 { get; set; }
        public Nullable<System.DateTime> SalesActivityField78 { get; set; }
        public Nullable<System.DateTime> SalesActivityField79 { get; set; }
        public Nullable<System.DateTime> SalesActivityField80 { get; set; }
    
        public virtual ContactMainTable ContactMainTable { get; set; }
    }
}
