//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserPropertiesTable
    {
        public int ID { get; set; }
        public int Type { get; set; }
        public byte[] Stream { get; set; }
        public long Version { get; set; }
    
        public virtual EntityTypesTable EntityTypesTable { get; set; }
    }
}
