//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFieldDefinition
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserFieldDefinition()
        {
            this.EntityUserFields = new HashSet<EntityUserField>();
        }
    
        public System.Guid FieldGUID { get; set; }
        public string FieldName { get; set; }
        public byte DataType { get; set; }
        public int DisplayFormat { get; set; }
        public short DataTableID { get; set; }
        public string PredefinedMetadataBlob { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<EntityUserField> EntityUserFields { get; set; }
        public virtual UserFieldDataType UserFieldDataType { get; set; }
        public virtual UserFieldTableId UserFieldTableId { get; set; }
    }
}
