//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BcmMigrationTool
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserFieldDataType
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public UserFieldDataType()
        {
            this.UserFieldDefinitions = new HashSet<UserFieldDefinition>();
        }
    
        public byte DataTypeID { get; set; }
        public string DataTypeName { get; set; }
        public short MapiDataTypeID { get; set; }
    
        public virtual DataTypesTable DataTypesTable { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<UserFieldDefinition> UserFieldDefinitions { get; set; }
    }
}
