// Generated by Xamasoft JSON Class Generator
// http://www.xamasoft.com/json-class-generator

using Newtonsoft.Json;

namespace BCM_Migration_Tool.Objects
{
    public partial class OCMActivity
    {
        public class InlineLinks2
        {
            [JsonProperty("Relationships")]
            public object[] Relationships;
        }
    }
    public partial class OCMActivity
    {

        [JsonProperty("Id")]
        public object Id;

        [JsonProperty("Subtype")]
        public string Subtype;

        [JsonProperty("ActionVerb")]
        public string ActionVerb;

        [JsonProperty("DisplayName")]
        public string DisplayName;

        [JsonProperty("EventTime")]
        public string EventTime;

        [JsonProperty("SourceUser")]
        public string SourceUser;

        //[JsonProperty("InlineLinks")]
        //public InlineLinks2 InlineLinks;

        [JsonProperty("ModifiedProperties")]
        public string ModifiedProperties;

        //[JsonProperty("LinkType")]
        //public string LinkType;

        //[JsonProperty("LinkedEntityNames")]
        //public string LinkedEntityNames;

        //[JsonProperty("TargetEntities", NullValueHandling = NullValueHandling.Ignore)]
        //public object[] TargetEntities;

        //[JsonProperty("OtherRelatedEntities", NullValueHandling = NullValueHandling.Ignore)]
        //public object[] OtherRelatedEntities;

        [JsonProperty("Text")]
        public string Text;

        [JsonProperty("XrmId", NullValueHandling = NullValueHandling.Ignore)]
        public object XrmId;
    }
}