//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace BCM_Migration_Tool.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("BCM_Migration_Tool.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Use this query to get all activities (across all entities - business contact, accounts, opportunities) in BCM to be migrated as OCM activity post/phone log
        ///*/
        ///SELECT
        ///		AT.[ActivityID]
        ///	   ,AC.ContactID
        ///	   ,CMT.EntryGUID
        ///	   ,CMT.Subject
        ///      ,AT.[ActivityGUID]
        ///      ,AT.[Subject]
        ///      ,AT.[ActivityNote]
        ///      ,AT.[ActivityDate] as CreatedOn
        ///      ,AT.[ActivityType] 
        ///  FROM   [dbo].[ActivitiesTable] AT
        ///  INNER JOIN  [dbo].[ActivityContacts] AC ON AT.ActivityID = AC.ActivityID
        ///  INNER JOI [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BCM_Activities {
            get {
                return ResourceManager.GetString("BCM_Activities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////* Getting User Custom Field Values*/
        ///
        ///-- (Generic) Datatype Mapping table (BCM datatype and SQL Data type) 
        ///  DECLARE @DataTypeMap TABLE (DateTypeID TINYINT, DataTypeName NVARCHAR(32))
        ///  INSERT INTO @DataTypeMap	VALUES	(1, &apos;NVARCHAR(MAX)&apos;),	-- Text
        ///									(2, &apos;NUMERIC(10,5)&apos;),	-- Number
        ///									(3, &apos;DECIMAL(5,2)&apos;),	-- Percent
        ///									(4, &apos;MONEY&apos;),			-- Currency
        ///									(5, &apos;BIT&apos;),				-- Y/N
        ///									(6, &apos;DATETIME&apos;),		-- Date/time
        ///									(7, &apos;BIGINT&apos;),			-- Integer
        ///									(8, &apos;NVARCHAR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BCM_CustomFields_Accounts {
            get {
                return ResourceManager.GetString("BCM_CustomFields_Accounts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////* Getting User Custom Field Values*/
        ///
        ///-- (Generic) Datatype Mapping table (BCM datatype and SQL Data type) 
        ///  DECLARE @DataTypeMap TABLE (DateTypeID TINYINT, DataTypeName NVARCHAR(32))
        ///  INSERT INTO @DataTypeMap	VALUES	(1, &apos;NVARCHAR(MAX)&apos;),	-- Text
        ///									(2, &apos;NUMERIC(10,5)&apos;),	-- Number
        ///									(3, &apos;DECIMAL(5,2)&apos;),	-- Percent
        ///									(4, &apos;MONEY&apos;),			-- Currency
        ///									(5, &apos;BIT&apos;),				-- Y/N
        ///									(6, &apos;DATETIME&apos;),		-- Date/time
        ///									(7, &apos;BIGINT&apos;),			-- Integer
        ///									(8, &apos;NVARCHAR [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BCM_CustomFields_Contacts {
            get {
                return ResourceManager.GetString("BCM_CustomFields_Contacts", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 
        ////* Getting User Custom Field Values*/
        ///
        ///-- Datatype Mapping table (BCM datatype and SQL Data type)
        ///  DECLARE @DataTypeMap TABLE (DateTypeID TINYINT, DataTypeName NVARCHAR(32))
        ///  INSERT INTO @DataTypeMap	VALUES	(1, &apos;NVARCHAR(MAX)&apos;),	-- Text
        ///									(2, &apos;NUMERIC(10,5)&apos;),	-- Number
        ///									(3, &apos;DECIMAL(5,2)&apos;),	-- Percent
        ///									(4, &apos;MONEY&apos;),			-- Currency
        ///									(5, &apos;BIT&apos;),				-- Y/N
        ///									(6, &apos;DATETIME&apos;),		-- Date/time
        ///									(7, &apos;BIGINT&apos;),			-- Integer
        ///									(8, &apos;NVARCHAR(MAX)&apos;),	-- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BCM_CustomFields_Opportunities {
            get {
                return ResourceManager.GetString("BCM_CustomFields_Opportunities", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /*
        ///Use this query to get the list of all BCM opportunities, its OOB field values and link to contact/company
        ///*/
        ///SELECT  OFV.[ContactServiceID]		
        ///      ,OFV.[OpportunityType]
        ///      ,OFV.[OpportunityStage]					-- [BCM] Deal Stage
        ///      ,OFV.[OpportunityCloseDate]				-- [BCM] Due Date
        ///      ,OFV.[OpportunityStatus]					
        ///      ,OFV.[Probability]						 
        ///      ,OFV.[OpportunityTotal]					-- [BCM] Deal Amount
        ///      ,OFV.[OpportunityExpectedRevenue]
        ///      ,OFV.[OpportunityTotalDiscount]
        ///      ,OFV.[Oppo [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BCM_Opportunity_Core {
            get {
                return ResourceManager.GetString("BCM_Opportunity_Core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* Use this query to get the list of BCM custom user fields*/
        ///SELECT UFD.[FieldGUID]
        ///      , UFD.[FieldName]
        ///	  , UFD.DataType as DataTypeID
        ///      , UFDT.[DataTypeName]
        ///	  ,EUF.UserFieldIndex
        ///	  , EUF.EntityType as EntityTypeID
        ///	  , ETT.EntityTypeName
        ///  FROM [dbo].[UserFieldDefinitions] UFD
        ///  INNER JOIN [dbo].[UserFieldDataTypes] UFDT on UFD.DataType = UFDT.DataTypeID
        ///  INNER JOIN [dbo].[EntityUserFields] EUF on EUF.FieldGUID = UFD.FieldGUID
        ///  INNER JOIN [dbo].[EntityTypesTable] ETT on EUF.Entity [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string BCM_UserFields {
            get {
                return ResourceManager.GetString("BCM_UserFields", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap BCMtool_icon {
            get {
                object obj = ResourceManager.GetObject("BCMtool_icon", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:m=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot; xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;t:RequestServerVersion Version=&quot;V2016_04_13&quot; /&gt;
        ///  &lt;/soap:Header&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;m:CreateXrmGraphRelationship&gt;
        ///      &lt;m:FromEntityId&gt;{FROMENTITYID}&lt;/m:FromEntityId&gt;
        ///      &lt;m:Fro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string CreateXrmGraphRelationshipRequest {
            get {
                return ResourceManager.GetString("CreateXrmGraphRelationshipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Deal_Stages {
            get {
                object obj = ResourceManager.GetObject("Deal_Stages", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:m=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot; xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;t:RequestServerVersion Version=&quot;V2016_04_13&quot; /&gt;
        ///  &lt;/soap:Header&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;m:DeleteXrmGraphRelationship&gt;
        ///      &lt;m:FromEntityId&gt;{FROMENTITYID}&lt;/m:FromEntityId&gt;
        ///      &lt;m:Fro [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string DeleteXrmGraphRelationshipRequest {
            get {
                return ResourceManager.GetString("DeleteXrmGraphRelationshipRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap downbutton {
            get {
                object obj = ResourceManager.GetObject("downbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot; xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot; xmlns:m=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;RequestServerVersion Version=&quot;V2016_02_10&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot; /&gt;
        ///  &lt;/soap:Header&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;m:FindPeople&gt;
        ///      &lt;m:IndexedPageItemView BasePoint=&quot;Beginning&quot; MaxEntriesReturned=&quot;10 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindPeopleRequest {
            get {
                return ResourceManager.GetString("FindPeopleRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;UTF-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;
        ///               xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;
        ///               xmlns:m=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;t:RequestServerVersion Version=&quot;V2016_02_10&quot; /&gt;
        ///  &lt;/soap:Header&gt;
        ///  &lt;soap:Body &gt;
        ///    &lt;m:FindPeople&gt;
        ///      &lt;m:PersonaShape&gt;
        ///        &lt;t:BaseShape&gt;Default&lt;/t:BaseShape&gt;
        ///        &lt;t:AdditionalProperties&gt;
        ///   [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string FindPeopleRequest2 {
            get {
                return ResourceManager.GetString("FindPeopleRequest2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;
        ///               xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;
        ///	&lt;soap:Header&gt;
        ///		&lt;t:RequestServerVersion Version=&quot;V2016_02_10&quot;/&gt;
        ///	&lt;/soap:Header&gt;
        ///	&lt;soap:Body xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;&gt;
        ///		&lt;GetPersona&gt;
        ///			&lt;PersonaId Id=&quot;{ID}&quot;/&gt;
        ///			&lt;AdditionalProperties&gt;
        ///				&lt;ExtendedFieldURI PropertySetId=&quot;1a417774-4779-47c1-9851-e42057495fca&quot; Prop [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string GetPersonaRequest {
            get {
                return ResourceManager.GetString("GetPersonaRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap plusbutton {
            get {
                object obj = ResourceManager.GetObject("plusbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rightbutton {
            get {
                object obj = ResourceManager.GetObject("rightbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap rightbuttonred {
            get {
                object obj = ResourceManager.GetObject("rightbuttonred", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_Blue {
            get {
                object obj = ResourceManager.GetObject("Settings_Blue", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap Settings_Gray {
            get {
                object obj = ResourceManager.GetObject("Settings_Gray", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot;
        ///xmlns:xsd=&quot;http://www.w3.org/2001/XMLSchema&quot;
        ///xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;
        ///xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;t:RequestServerVersion Version=&quot;V2016_04_13&quot; /&gt;
        ///  &lt;/soap:Header&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;MoveItem xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot;
        ///    xmlns:t=&quot;http://schemas.microsoft.com/ [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ShareContactsRequest {
            get {
                return ResourceManager.GetString("ShareContactsRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot;?&gt;
        ///&lt;soap:Envelope xmlns:xsi=&quot;http://www.w3.org/2001/XMLSchema-instance&quot; xmlns:m=&quot;http://schemas.microsoft.com/exchange/services/2006/messages&quot; xmlns:t=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot; xmlns:soap=&quot;http://schemas.xmlsoap.org/soap/envelope/&quot;&gt;
        ///  &lt;soap:Header&gt;
        ///    &lt;RequestServerVersion Version=&quot;V2016_04_13&quot; xmlns=&quot;http://schemas.microsoft.com/exchange/services/2006/types&quot; /&gt;
        ///  &lt;/soap:Header&gt;
        ///  &lt;soap:Body&gt;
        ///    &lt;m:StartXrmSession&gt;
        ///      &lt;m:FailO [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string StartXrmSessionXMLRequest {
            get {
                return ResourceManager.GetString("StartXrmSessionXMLRequest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {&quot;Id&quot;:null,&quot;DisplayName&quot;:&quot;Alpha Corp&quot;,&quot;BusinessAddress&quot;:{&quot;Street&quot;:&quot;&quot;,&quot;City&quot;:&quot;&quot;,&quot;State&quot;:&quot;&quot;,&quot;CountryOrRegion&quot;:&quot;&quot;,&quot;PostalCode&quot;:&quot;&quot;},&quot;BusinessHomePage&quot;:&quot;www.alpha.com&quot;,&quot;BusinessPhones&quot;:[],&quot;EmailAddresses&quot;:[],&quot;Manager&quot;:null,&quot;Profession&quot;:null,&quot;TickerSymbol&quot;:null,&quot;Notes&quot;:null,&quot;XrmContactType&quot;:0,&quot;XrmCompanySize&quot;:0,&quot;XrmId&quot;:null}.
        /// </summary>
        internal static string TestAccountCreateJSON {
            get {
                return ResourceManager.GetString("TestAccountCreateJSON", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap trash {
            get {
                object obj = ResourceManager.GetObject("trash", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap upbutton {
            get {
                object obj = ResourceManager.GetObject("upbutton", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WizardStep1 {
            get {
                object obj = ResourceManager.GetObject("WizardStep1", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WizardStep2 {
            get {
                object obj = ResourceManager.GetObject("WizardStep2", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Bitmap.
        /// </summary>
        internal static System.Drawing.Bitmap WizardStep3 {
            get {
                object obj = ResourceManager.GetObject("WizardStep3", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
    }
}
